### ISSUE TITLE
Link to new version of Pandas Cookbook tutorials

### ISSUE THREAD

**Issue by Winterflower** [pydata/pandas-website#36]
This section links to old versions of the notebooks. 
http://pandas.pydata.org/pandas-docs/stable/tutorials.html

@jvns has updates the notebooks.

**Comment by Winterflower** [comment]
Okay, this s actually an issue in the docs and not the website. Hence closing issue.

**Comment by jorisvandenbossche** [comment]
@Winterflower did you open an issue at https://github.com/pydata/pydata/pandas ?

**Comment by Winterflower** [comment]
@jorisvandenbossche I did consider it, but then I saw this on the docs webstie

```
Here are links to the v0.1 release. For an up-to-date table of contents, see the pandas-cookbook GitHub repository. 
```

And I decided not to, but I'd be happy to remove the text above and update the links.

**Comment by jvns** [comment]
I just made a new v0.2 release: https://github.com/jvns/pandas-cookbook/releases/tag/v0.2

Some of the filenames have changed since version 0.1, so it'll be a little bit of work to make the links work again. (which is why I kept them at 0.1 in the first place, so that the links wouldn't break). 

Chapter 9 is also missing from the table of contents.

**Comment by jorisvandenbossche** [comment]
@jvns If you want to make a PR, updating the links to versions 0.2, very welcome!

**Comment by jorisvandenbossche** [comment]
Ah, I see @jreback already made an issue for that https://github.com/jvns/pandas-cookbook/issues/32
